clean

diff --git a/.github/workflows/tf-unit-tests.yml b/.github/workflows/tf-unit-tests.yml
--- a/.github/workflows/tf-unit-tests.yml
+++ b/.github/workflows/tf-unit-tests.yml
@@ -30,28 +30,28 @@ jobs:
       run: terraform fmt -check -recursive
     
     # # Perform security scan with TFsec
-    - name: Set up Go
-      uses: actions/setup-go@v3
-      with:
-        go-version: 'stable'
+    # - name: Set up Go
+    #   uses: actions/setup-go@v3
+    #   with:
+    #     go-version: 'stable'
   
-    - name: Install tfsec
-      run: go install github.com/aquasecurity/tfsec/cmd/tfsec@latest 
+    # - name: Install tfsec
+    #   run: go install github.com/aquasecurity/tfsec/cmd/tfsec@latest 
   
-    - name: Run tfsec
-      run: tfsec
+    # - name: Run tfsec
+    #   run: tfsec
 
-    # Perform a security scan of the terraform code using checkov
-    - name: Run Checkov action
-      id: checkov
-      uses: bridgecrewio/checkov-action@master
-      with: 
-        framework: terraform
+    # # Perform a security scan of the terraform code using checkov
+    # - name: Run Checkov action
+    #   id: checkov
+    #   uses: bridgecrewio/checkov-action@master
+    #   with: 
+    #     framework: terraform
 
-    # Upload results to GitHub Advanced Security
-    - name: Upload SARIF file
-      if: success() || failure()
-      uses: github/codeql-action/upload-sarif@v2
-      with:
-        sarif_file: results.sarif
-        category: checkov
+    # # Upload results to GitHub Advanced Security
+    # - name: Upload SARIF file
+    #   if: success() || failure()
+    #   uses: github/codeql-action/upload-sarif@v2
+    #   with:
+    #     sarif_file: results.sarif
+    #     category: checkov
